### ISSUE TITLE
Add a Github Action that transpiles Typescript components into Javascript

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery-components#169]
## Why? 
We recently fixed [a long standing bug](https://github.com/near/near-discovery-components/pull/165) in our Discussions component that is the perfect example of the types of errors that Typescript would prevent. 

## Solution
Allow contributors to this repo to write components in Typescript by introducing updating the existing github actions to include a step that transpiles Typescript components into javascript prior to committing components to the BOS.

## Concerns

1. Can we do this in a way that minimally reduces the legibility of source code when [viewed in BOS](https://near.org/near/widget/ComponentDetailsPage?src=near/widget/NestedDiscussions.Preview), 
2. Might this reduced legibility have implications on how likely developers are to reuse components

**Comment by mpeterdev** [comment]
I've spent quite a bit of time thinking through this before and experimenting with it. I believe the two concerns listed are pretty impactful. We want to avoid a scenario where users feel they have to go outside of BOS (to GitHub) in order to fork a component properly.

Some previous conversation occurred [here](https://github.com/NearSocial/viewer/discussions/110) but I will summarize:

One idea I've had is to save both the TS and JS versions on chain together, so that they JS is downloaded and executed by the VM but the TS is used for future code component development. Besides increased storage, the main challenge would be that there must exist a guarantee that the JS being executed was generated from the TS, otherwise authors could write seemingly benign TS and then slip some malicious behavior directly into the JS. My current thinking on the best way around that—but I am unsure of feasibility—is to have the transpilation performed by a smart contract. 

[SWC](https://swc.rs/) is a highly efficient transpiler built in Rust that is used by Next.js. If we were able to get that running in a smart contract, then we could change the process for writing BOS component code to SocialDB to always be piped through there first. Basically you submit code to the transpiler contract then it—and only it—is allowed to save component code to BOS.

**Comment by mpeterdev** [comment]
I also toyed with saving TS to SocialDB as-is then using SWC as WASM to transpile on the fly when loading components, I didn't make much progress due to time constraints but my suspicion is that performance will suffer

**Comment by shelegdmitriy** [comment]
I think we can use this project https://github.com/frol/bos-component-ts-starter to solve our issue. From now it's not about github actions. Using `bos-component-ts-starter` will help us to avoid a lot of errors.

I'd like to try it on this repo and  rewrite a DIG components folder using typescript at first. Then I'll compare both versions of components. If everything will be OK then I think we should do the same for `Posts`, `Feed`, etc

**Comment by charleslavon** [comment]
@shelegdmitriy what are your thoughts on this challenge that Michael mentioned? 

> challenge would be that there must exist a guarantee that the JS being executed was generated from the TS, otherwise authors could write seemingly benign TS and then slip some malicious behavior directly into the JS. My current thinking on the best way around that—but I am unsure of feasibility—is to have the transpilation performed by a smart contract.

**Comment by frol** [comment]
> challenge would be that there must exist a guarantee that the JS being executed was generated from the TS, otherwise authors could write seemingly benign TS and then slip some malicious behavior directly into the JS. My current thinking on the best way around that—but I am unsure of feasibility—is to have the transpilation performed by a smart contract.

My ts-starter does not obfuscate the original code, so it is as readable as any other BOS component, so I don't think it makes the situation any worse than it is now:

* The source code: https://github.com/frol/bos-component-ts-starter/blob/main/src/components/pages/homepage.tsx
* The code on chain: https://near.org/near/widget/ComponentDetailsPage?src=frol.near/widget/bos-component-ts-starter.components.pages.homepage&tab=source

<img width="1389" alt="image" src="https://github.com/near/near-discovery-components/assets/304265/9a92daa4-91fa-43e9-8f4a-0d76a23b7bd7">

**Comment by mpeterdev** [comment]
Ah okay cool, I agree that the output is totally reasonable. Thanks for the concrete example

**Comment by charleslavon** [comment]
Closing in favor of typescript in BOS Web Engine components.
