### ISSUE TITLE
Determine RoC development flow for building out DIG components

### ISSUE THREAD

**Issue by calebjacob** [near/near-discovery-components#757]
This ticket aims to get answers for the following:

- How might we approach rebuilding our DIG UI components as RoC components?
- Would this require a new repo, or a sub-folder in near-discovery-components? 
- How would we deploy these components into RoC namespace in SocialDB?

I'd like to see us spin up a brand new repo for our RoC components to give us mental separation between RoC and VM components. RoC components use TypeScript and CSS Modules - so their tooling is very different from our existing VM components.

Next Steps:

- [x] Sync up with @mpeterdev and @andy-haynes to figure out if we've ironed out the tooling for developing/viewing RoC components in a local environment (editing inside VS Code) and publishing those RoC components to an account via GitHub action.

If we determine the ideal local development flow isn't ready yet, we could start building out our `DIG` components via the online sandbox: https://roc-sandbox.near.dev

**Comment by mpeterdev** [comment]
> Would this require a new repo, or a sub-folder in near-discovery-components?

If we expect to be migrating components, then you could keep them in the same repo so that contributor history isn't lost.

If we expect to be implementing a new set of components without building too much off existing work, then a fresh repo would be fitting.

There isn't much functional difference between the two, go with whatever feels right.

> publishing those RoC components to an account via GitHub action

CI/CD publishing is available as of a few weeks ago. We are using it to publish `apps/demos` from `near/bos-web-engine`. See [this action](https://github.com/near/bos-web-engine/blob/main/.github/workflows/deploy-components-main.yml) which uses my fork of `bos-cli-rs` for deploy

> How would we deploy these components into RoC namespace in SocialDB?

This is part of the workflow, note the first arg in the deploy command
```sh
./bos components --social-db-folder "component_alpha" deploy ...
```

> if we've ironed out the tooling for developing/viewing RoC components in a local environment (editing inside VS Code)

bos-loader support came back online around the same time, you can set the URL via the collapsible dev tools on roc.near.dev

We haven't done any work towards bringing the VS Code experience in line with sandbox as far TypeScript support, so it's up to you whether you do your work in sandbox or VS code. If you choose to use Sandbox, I would still recommend copy/pasting out to a git repo for commits and publishing to enable a proper team workflow

**Comment by calebjacob** [comment]
Fantastic. Thanks for the response @mpeterdev! That gives me enough direction for now to play around with setting up a new repo. I might have some more follow up questions in a day or two.

**Comment by calebjacob** [comment]
I've got a new repository set up and working end to end: https://github.com/near/near-roc-components

The README has detailed steps on how to get up and running. We'll just want to consider what other documentation and automation we need to copy over from our `near-discovery-components` repo @charleslavon (eg: contribution guidelines).

I also went ahead and worked on a solution to improve DX further by enabling hot reloading when developing components locally: https://github.com/near/bos-web-engine/pull/420
